# Site settings
title: HumanBrains Blog
email: info@humanbrains.tech
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  humanbrainstech
google_play: 
google_plus_com:   # Community link
google_plus_per:   # Personal link
facebook_app_id: 

# Layout settings
header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]

more_vert:
  option1:
    name: View on GitHub
    link: https://github.io/humanbrainstech/humanbrainstech.github.io

disqus: false

# Build settings
markdown: kramdown

exclude: [CHANGELOG.md, LICENSE, README.md, Gemfile, Gemfile.lock]


